import random

#could so-called secondary composition cases in native vocabulary (McCone 1997:90-1) be burps from a bigrammatic grammar? 
#should make separate lists of native/loan secondary orderings

#this holds counts of raw appearance of the prefix combinations (including all alternative orderings. specific counts of alternative orderings should be collated in different lists) -> mind inversion to avoid word initial position
#if populated by script, should be lists, not tuples
#cum1, ad1, ro1 are 'lexical', cum2, ad2, ro2 are augments

#-> probably need to add in the particles too ...

combination_cnt = (
    [('to',), None],
    [('for',), None],
    [('fris',), None],
    [('eter',), None],
    [('imbe',), None],
    [('ess',), None],
    [('fo',), None],
    [('inde',), None],
    [('ad1',), None],
    [('ad2',), None],
    [('athe',), None],
    [('are',), None],
    [('de',), None],
    [('cum1',), None],
    [('cum2',), None],
    [('ro1',), None],
    [('ro2',), None],
    [('uss',), None],
    [('ne',), None],
    [('to', 'for'), None],
    [('to', 'fris'), None],
    [('to', 'eter'), None],
    [('to', 'imbe'), None],
    [('to', 'ess'), None],
    [('to', 'fo'), None],
    [('to', 'inde'), None],
    [('to', 'ad1'), None],
    [('to', 'ad2'), None],
    [('to', 'athe'), None],
    [('to', 'are'), None],
    [('to', 'de'), None],
    [('to', 'cum1'), None],
    [('to', 'cum2'), None],
    [('to', 'ro1'), None],
    [('to', 'ro2'), None],
    [('to', 'uss'), None],
    [('to', 'ne'), None],
    [('for', 'ad1'), None],
    [('for', 'ad2'), None],
    [('for', 'athe'), None],
    [('for', 'are'), None],
    [('for', 'de'), None],
    [('fris', 'ad1'), None],
    [('fris', 'ad2'), None],
    [('fris', 'athe'), None],
    [('fris', 'are'), None],
    [('fris', 'de'), None],
    [('eter', 'ad1'), None],
    [('eter', 'ad2'), None],
    [('eter', 'athe'), None],
    [('eter', 'are'), None],
    [('eter', 'de'), None],
    [('imbe', 'ad1'), None],
    [('imbe', 'ad2'), None],
    [('imbe', 'athe'), None],
    [('imbe', 'are'), None],
    [('imbe', 'de'), None],
    [('ess', 'ad1'), None],
    [('ess', 'ad2'), None],
    [('ess', 'athe'), None],
    [('ess', 'are'), None],
    [('ess', 'de'), None],
    [('fo', 'ad1'), None],
    [('fo', 'ad2'), None],
    [('fo', 'athe'), None],
    [('fo', 'are'), None],
    [('fo', 'de'), None],
    [('inde', 'ad1'), None],
    [('inde', 'ad2'), None],
    [('inde', 'athe'), None],
    [('inde', 'are'), None],
    [('inde', 'de'), None],
    [('for', 'cum1'), None],
    [('for', 'cum2'), None],
    [('for', 'ro1'), None],
    [('for', 'ro2'), None],
    [('fris', 'cum1'), None],
    [('fris', 'cum2'), None],
    [('fris', 'ro1'), None],
    [('fris', 'ro2'), None],
    [('eter', 'cum1'), None],
    [('eter', 'cum2'), None],
    [('eter', 'ro1'), None],
    [('eter', 'ro2'), None],
    [('imbe', 'cum1'), None],
    [('imbe', 'cum2'), None],
    [('imbe', 'ro1'), None],
    [('imbe', 'ro2'), None],
    [('ess', 'cum1'), None],
    [('ess', 'cum2'), None],
    [('ess', 'ro1'), None],
    [('ess', 'ro2'), None],
    [('fo', 'cum1'), None],
    [('fo', 'cum2'), None],
    [('fo', 'ro1'), None],
    [('fo', 'ro2'), None],
    [('inde', 'cum1'), None],
    [('inde', 'cum2'), None],
    [('inde', 'ro1'), None],
    [('inde', 'ro2'), None],
    [('for', 'uss'), None],
    [('for', 'ne'), None],
    [('fris', 'uss'), None],
    [('fris', 'ne'), None],
    [('eter', 'uss'), None],
    [('eter', 'ne'), None],
    [('imbe', 'uss'), None],
    [('imbe', 'ne'), None],
    [('ess', 'uss'), None],
    [('ess', 'ne'), None],
    [('fo', 'uss'), None],
    [('fo', 'ne'), None],
    [('inde', 'uss'), None],
    [('inde', 'ne'), None],
    [('ad1', 'cum1'), None],
    [('ad1', 'cum2'), None],
    [('ad1', 'ro1'), None],
    [('ad1', 'ro2'), None],
    [('ad2', 'cum1'), None],
    [('ad2', 'cum2'), None],
    [('ad2', 'ro1'), None],
    [('ad2', 'ro2'), None],
    [('athe', 'cum1'), None],
    [('athe', 'cum2'), None],
    [('athe', 'ro1'), None],
    [('athe', 'ro2'), None],
    [('are', 'cum1'), None],
    [('are', 'cum2'), None],
    [('are', 'ro1'), None],
    [('are', 'ro2'), None],
    [('de', 'cum1'), None],
    [('de', 'cum2'), None],
    [('de', 'ro1'), None],
    [('de', 'ro2'), None],
    [('ad1', 'uss'), None],
    [('ad1', 'ne'), None],
    [('ad2', 'uss'), None],
    [('ad2', 'ne'), None],
    [('athe', 'uss'), None],
    [('athe', 'ne'), None],
    [('are', 'uss'), None],
    [('are', 'ne'), None],
    [('de', 'uss'), None],
    [('de', 'ne'), None],
    [('cum1', 'uss'), None],
    [('cum1', 'ne'), None],
    [('cum2', 'uss'), None],
    [('cum2', 'ne'), None],
    [('ro1', 'uss'), None],
    [('ro1', 'ne'), None],
    [('ro2', 'uss'), None],
    [('ro2', 'ne'), None],
    [('to', 'for', 'ad1'), None],
    [('to', 'for', 'ad2'), None],
    [('to', 'for', 'athe'), None],
    [('to', 'for', 'are'), None],
    [('to', 'for', 'de'), None],
    [('to', 'fris', 'ad1'), None],
    [('to', 'fris', 'ad2'), None],
    [('to', 'fris', 'athe'), None],
    [('to', 'fris', 'are'), None],
    [('to', 'fris', 'de'), None],
    [('to', 'eter', 'ad1'), None],
    [('to', 'eter', 'ad2'), None],
    [('to', 'eter', 'athe'), None],
    [('to', 'eter', 'are'), None],
    [('to', 'eter', 'de'), None],
    [('to', 'imbe', 'ad1'), None],
    [('to', 'imbe', 'ad2'), None],
    [('to', 'imbe', 'athe'), None],
    [('to', 'imbe', 'are'), None],
    [('to', 'imbe', 'de'), None],
    [('to', 'ess', 'ad1'), None],
    [('to', 'ess', 'ad2'), None],
    [('to', 'ess', 'athe'), None],
    [('to', 'ess', 'are'), None],
    [('to', 'ess', 'de'), None],
    [('to', 'fo', 'ad1'), None],
    [('to', 'fo', 'ad2'), None],
    [('to', 'fo', 'athe'), None],
    [('to', 'fo', 'are'), None],
    [('to', 'fo', 'de'), None],
    [('to', 'inde', 'ad1'), None],
    [('to', 'inde', 'ad2'), None],
    [('to', 'inde', 'athe'), None],
    [('to', 'inde', 'are'), None],
    [('to', 'inde', 'de'), None],
    [('to', 'for', 'cum1'), None],
    [('to', 'for', 'cum2'), None],
    [('to', 'for', 'ro1'), None],
    [('to', 'for', 'ro2'), None],
    [('to', 'fris', 'cum1'), None],
    [('to', 'fris', 'cum2'), None],
    [('to', 'fris', 'ro1'), None],
    [('to', 'fris', 'ro2'), None],
    [('to', 'eter', 'cum1'), None],
    [('to', 'eter', 'cum2'), None],
    [('to', 'eter', 'ro1'), None],
    [('to', 'eter', 'ro2'), None],
    [('to', 'imbe', 'cum1'), None],
    [('to', 'imbe', 'cum2'), None],
    [('to', 'imbe', 'ro1'), None],
    [('to', 'imbe', 'ro2'), None],
    [('to', 'ess', 'cum1'), None],
    [('to', 'ess', 'cum2'), None],
    [('to', 'ess', 'ro1'), None],
    [('to', 'ess', 'ro2'), None],
    [('to', 'fo', 'cum1'), None],
    [('to', 'fo', 'cum2'), None],
    [('to', 'fo', 'ro1'), None],
    [('to', 'fo', 'ro2'), None],
    [('to', 'inde', 'cum1'), None],
    [('to', 'inde', 'cum2'), None],
    [('to', 'inde', 'ro1'), None],
    [('to', 'inde', 'ro2'), None],
    [('to', 'for', 'uss'), None],
    [('to', 'for', 'ne'), None],
    [('to', 'fris', 'uss'), None],
    [('to', 'fris', 'ne'), None],
    [('to', 'eter', 'uss'), None],
    [('to', 'eter', 'ne'), None],
    [('to', 'imbe', 'uss'), None],
    [('to', 'imbe', 'ne'), None],
    [('to', 'ess', 'uss'), None],
    [('to', 'ess', 'ne'), None],
    [('to', 'fo', 'uss'), None],
    [('to', 'fo', 'ne'), None],
    [('to', 'inde', 'uss'), None],
    [('to', 'inde', 'ne'), None],
    [('to', 'ad1', 'cum1'), None],
    [('to', 'ad1', 'cum2'), None],
    [('to', 'ad1', 'ro1'), None],
    [('to', 'ad1', 'ro2'), None],
    [('to', 'ad2', 'cum1'), None],
    [('to', 'ad2', 'cum2'), None],
    [('to', 'ad2', 'ro1'), None],
    [('to', 'ad2', 'ro2'), None],
    [('to', 'athe', 'cum1'), None],
    [('to', 'athe', 'cum2'), None],
    [('to', 'athe', 'ro1'), None],
    [('to', 'athe', 'ro2'), None],
    [('to', 'are', 'cum1'), None],
    [('to', 'are', 'cum2'), None],
    [('to', 'are', 'ro1'), None],
    [('to', 'are', 'ro2'), None],
    [('to', 'de', 'cum1'), None],
    [('to', 'de', 'cum2'), None],
    [('to', 'de', 'ro1'), None],
    [('to', 'de', 'ro2'), None],
    [('to', 'ad1', 'uss'), None],
    [('to', 'ad1', 'ne'), None],
    [('to', 'ad2', 'uss'), None],
    [('to', 'ad2', 'ne'), None],
    [('to', 'athe', 'uss'), None],
    [('to', 'athe', 'ne'), None],
    [('to', 'are', 'uss'), None],
    [('to', 'are', 'ne'), None],
    [('to', 'de', 'uss'), None],
    [('to', 'de', 'ne'), None],
    [('to', 'cum1', 'uss'), None],
    [('to', 'cum1', 'ne'), None],
    [('to', 'cum2', 'uss'), None],
    [('to', 'cum2', 'ne'), None],
    [('to', 'ro1', 'uss'), None],
    [('to', 'ro1', 'ne'), None],
    [('to', 'ro2', 'uss'), None],
    [('to', 'ro2', 'ne'), None],
    [('for', 'ad1', 'cum1'), None],
    [('for', 'ad1', 'cum2'), None],
    [('for', 'ad1', 'ro1'), None],
    [('for', 'ad1', 'ro2'), None],
    [('for', 'ad2', 'cum1'), None],
    [('for', 'ad2', 'cum2'), None],
    [('for', 'ad2', 'ro1'), None],
    [('for', 'ad2', 'ro2'), None],
    [('for', 'athe', 'cum1'), None],
    [('for', 'athe', 'cum2'), None],
    [('for', 'athe', 'ro1'), None],
    [('for', 'athe', 'ro2'), None],
    [('for', 'are', 'cum1'), None],
    [('for', 'are', 'cum2'), None],
    [('for', 'are', 'ro1'), None],
    [('for', 'are', 'ro2'), None],
    [('for', 'de', 'cum1'), None],
    [('for', 'de', 'cum2'), None],
    [('for', 'de', 'ro1'), None],
    [('for', 'de', 'ro2'), None],
    [('fris', 'ad1', 'cum1'), None],
    [('fris', 'ad1', 'cum2'), None],
    [('fris', 'ad1', 'ro1'), None],
    [('fris', 'ad1', 'ro2'), None],
    [('fris', 'ad2', 'cum1'), None],
    [('fris', 'ad2', 'cum2'), None],
    [('fris', 'ad2', 'ro1'), None],
    [('fris', 'ad2', 'ro2'), None],
    [('fris', 'athe', 'cum1'), None],
    [('fris', 'athe', 'cum2'), None],
    [('fris', 'athe', 'ro1'), None],
    [('fris', 'athe', 'ro2'), None],
    [('fris', 'are', 'cum1'), None],
    [('fris', 'are', 'cum2'), None],
    [('fris', 'are', 'ro1'), None],
    [('fris', 'are', 'ro2'), None],
    [('fris', 'de', 'cum1'), None],
    [('fris', 'de', 'cum2'), None],
    [('fris', 'de', 'ro1'), None],
    [('fris', 'de', 'ro2'), None],
    [('eter', 'ad1', 'cum1'), None],
    [('eter', 'ad1', 'cum2'), None],
    [('eter', 'ad1', 'ro1'), None],
    [('eter', 'ad1', 'ro2'), None],
    [('eter', 'ad2', 'cum1'), None],
    [('eter', 'ad2', 'cum2'), None],
    [('eter', 'ad2', 'ro1'), None],
    [('eter', 'ad2', 'ro2'), None],
    [('eter', 'athe', 'cum1'), None],
    [('eter', 'athe', 'cum2'), None],
    [('eter', 'athe', 'ro1'), None],
    [('eter', 'athe', 'ro2'), None],
    [('eter', 'are', 'cum1'), None],
    [('eter', 'are', 'cum2'), None],
    [('eter', 'are', 'ro1'), None],
    [('eter', 'are', 'ro2'), None],
    [('eter', 'de', 'cum1'), None],
    [('eter', 'de', 'cum2'), None],
    [('eter', 'de', 'ro1'), None],
    [('eter', 'de', 'ro2'), None],
    [('imbe', 'ad1', 'cum1'), None],
    [('imbe', 'ad1', 'cum2'), None],
    [('imbe', 'ad1', 'ro1'), None],
    [('imbe', 'ad1', 'ro2'), None],
    [('imbe', 'ad2', 'cum1'), None],
    [('imbe', 'ad2', 'cum2'), None],
    [('imbe', 'ad2', 'ro1'), None],
    [('imbe', 'ad2', 'ro2'), None],
    [('imbe', 'athe', 'cum1'), None],
    [('imbe', 'athe', 'cum2'), None],
    [('imbe', 'athe', 'ro1'), None],
    [('imbe', 'athe', 'ro2'), None],
    [('imbe', 'are', 'cum1'), None],
    [('imbe', 'are', 'cum2'), None],
    [('imbe', 'are', 'ro1'), None],
    [('imbe', 'are', 'ro2'), None],
    [('imbe', 'de', 'cum1'), None],
    [('imbe', 'de', 'cum2'), None],
    [('imbe', 'de', 'ro1'), None],
    [('imbe', 'de', 'ro2'), None],
    [('ess', 'ad1', 'cum1'), None],
    [('ess', 'ad1', 'cum2'), None],
    [('ess', 'ad1', 'ro1'), None],
    [('ess', 'ad1', 'ro2'), None],
    [('ess', 'ad2', 'cum1'), None],
    [('ess', 'ad2', 'cum2'), None],
    [('ess', 'ad2', 'ro1'), None],
    [('ess', 'ad2', 'ro2'), None],
    [('ess', 'athe', 'cum1'), None],
    [('ess', 'athe', 'cum2'), None],
    [('ess', 'athe', 'ro1'), None],
    [('ess', 'athe', 'ro2'), None],
    [('ess', 'are', 'cum1'), None],
    [('ess', 'are', 'cum2'), None],
    [('ess', 'are', 'ro1'), None],
    [('ess', 'are', 'ro2'), None],
    [('ess', 'de', 'cum1'), None],
    [('ess', 'de', 'cum2'), None],
    [('ess', 'de', 'ro1'), None],
    [('ess', 'de', 'ro2'), None],
    [('fo', 'ad1', 'cum1'), None],
    [('fo', 'ad1', 'cum2'), None],
    [('fo', 'ad1', 'ro1'), None],
    [('fo', 'ad1', 'ro2'), None],
    [('fo', 'ad2', 'cum1'), None],
    [('fo', 'ad2', 'cum2'), None],
    [('fo', 'ad2', 'ro1'), None],
    [('fo', 'ad2', 'ro2'), None],
    [('fo', 'athe', 'cum1'), None],
    [('fo', 'athe', 'cum2'), None],
    [('fo', 'athe', 'ro1'), None],
    [('fo', 'athe', 'ro2'), None],
    [('fo', 'are', 'cum1'), None],
    [('fo', 'are', 'cum2'), None],
    [('fo', 'are', 'ro1'), None],
    [('fo', 'are', 'ro2'), None],
    [('fo', 'de', 'cum1'), None],
    [('fo', 'de', 'cum2'), None],
    [('fo', 'de', 'ro1'), None],
    [('fo', 'de', 'ro2'), None],
    [('inde', 'ad1', 'cum1'), None],
    [('inde', 'ad1', 'cum2'), None],
    [('inde', 'ad1', 'ro1'), None],
    [('inde', 'ad1', 'ro2'), None],
    [('inde', 'ad2', 'cum1'), None],
    [('inde', 'ad2', 'cum2'), None],
    [('inde', 'ad2', 'ro1'), None],
    [('inde', 'ad2', 'ro2'), None],
    [('inde', 'athe', 'cum1'), None],
    [('inde', 'athe', 'cum2'), None],
    [('inde', 'athe', 'ro1'), None],
    [('inde', 'athe', 'ro2'), None],
    [('inde', 'are', 'cum1'), None],
    [('inde', 'are', 'cum2'), None],
    [('inde', 'are', 'ro1'), None],
    [('inde', 'are', 'ro2'), None],
    [('inde', 'de', 'cum1'), None],
    [('inde', 'de', 'cum2'), None],
    [('inde', 'de', 'ro1'), None],
    [('inde', 'de', 'ro2'), None],
    [('for', 'ad1', 'uss'), None],
    [('for', 'ad1', 'ne'), None],
    [('for', 'ad2', 'uss'), None],
    [('for', 'ad2', 'ne'), None],
    [('for', 'athe', 'uss'), None],
    [('for', 'athe', 'ne'), None],
    [('for', 'are', 'uss'), None],
    [('for', 'are', 'ne'), None],
    [('for', 'de', 'uss'), None],
    [('for', 'de', 'ne'), None],
    [('fris', 'ad1', 'uss'), None],
    [('fris', 'ad1', 'ne'), None],
    [('fris', 'ad2', 'uss'), None],
    [('fris', 'ad2', 'ne'), None],
    [('fris', 'athe', 'uss'), None],
    [('fris', 'athe', 'ne'), None],
    [('fris', 'are', 'uss'), None],
    [('fris', 'are', 'ne'), None],
    [('fris', 'de', 'uss'), None],
    [('fris', 'de', 'ne'), None],
    [('eter', 'ad1', 'uss'), None],
    [('eter', 'ad1', 'ne'), None],
    [('eter', 'ad2', 'uss'), None],
    [('eter', 'ad2', 'ne'), None],
    [('eter', 'athe', 'uss'), None],
    [('eter', 'athe', 'ne'), None],
    [('eter', 'are', 'uss'), None],
    [('eter', 'are', 'ne'), None],
    [('eter', 'de', 'uss'), None],
    [('eter', 'de', 'ne'), None],
    [('imbe', 'ad1', 'uss'), None],
    [('imbe', 'ad1', 'ne'), None],
    [('imbe', 'ad2', 'uss'), None],
    [('imbe', 'ad2', 'ne'), None],
    [('imbe', 'athe', 'uss'), None],
    [('imbe', 'athe', 'ne'), None],
    [('imbe', 'are', 'uss'), None],
    [('imbe', 'are', 'ne'), None],
    [('imbe', 'de', 'uss'), None],
    [('imbe', 'de', 'ne'), None],
    [('ess', 'ad1', 'uss'), None],
    [('ess', 'ad1', 'ne'), None],
    [('ess', 'ad2', 'uss'), None],
    [('ess', 'ad2', 'ne'), None],
    [('ess', 'athe', 'uss'), None],
    [('ess', 'athe', 'ne'), None],
    [('ess', 'are', 'uss'), None],
    [('ess', 'are', 'ne'), None],
    [('ess', 'de', 'uss'), None],
    [('ess', 'de', 'ne'), None],
    [('fo', 'ad1', 'uss'), None],
    [('fo', 'ad1', 'ne'), None],
    [('fo', 'ad2', 'uss'), None],
    [('fo', 'ad2', 'ne'), None],
    [('fo', 'athe', 'uss'), None],
    [('fo', 'athe', 'ne'), None],
    [('fo', 'are', 'uss'), None],
    [('fo', 'are', 'ne'), None],
    [('fo', 'de', 'uss'), None],
    [('fo', 'de', 'ne'), None],
    [('inde', 'ad1', 'uss'), None],
    [('inde', 'ad1', 'ne'), None],
    [('inde', 'ad2', 'uss'), None],
    [('inde', 'ad2', 'ne'), None],
    [('inde', 'athe', 'uss'), None],
    [('inde', 'athe', 'ne'), None],
    [('inde', 'are', 'uss'), None],
    [('inde', 'are', 'ne'), None],
    [('inde', 'de', 'uss'), None],
    [('inde', 'de', 'ne'), None],
    [('for', 'cum1', 'uss'), None],
    [('for', 'cum1', 'ne'), None],
    [('for', 'cum2', 'uss'), None],
    [('for', 'cum2', 'ne'), None],
    [('for', 'ro1', 'uss'), None],
    [('for', 'ro1', 'ne'), None],
    [('for', 'ro2', 'uss'), None],
    [('for', 'ro2', 'ne'), None],
    [('fris', 'cum1', 'uss'), None],
    [('fris', 'cum1', 'ne'), None],
    [('fris', 'cum2', 'uss'), None],
    [('fris', 'cum2', 'ne'), None],
    [('fris', 'ro1', 'uss'), None],
    [('fris', 'ro1', 'ne'), None],
    [('fris', 'ro2', 'uss'), None],
    [('fris', 'ro2', 'ne'), None],
    [('eter', 'cum1', 'uss'), None],
    [('eter', 'cum1', 'ne'), None],
    [('eter', 'cum2', 'uss'), None],
    [('eter', 'cum2', 'ne'), None],
    [('eter', 'ro1', 'uss'), None],
    [('eter', 'ro1', 'ne'), None],
    [('eter', 'ro2', 'uss'), None],
    [('eter', 'ro2', 'ne'), None],
    [('imbe', 'cum1', 'uss'), None],
    [('imbe', 'cum1', 'ne'), None],
    [('imbe', 'cum2', 'uss'), None],
    [('imbe', 'cum2', 'ne'), None],
    [('imbe', 'ro1', 'uss'), None],
    [('imbe', 'ro1', 'ne'), None],
    [('imbe', 'ro2', 'uss'), None],
    [('imbe', 'ro2', 'ne'), None],
    [('ess', 'cum1', 'uss'), None],
    [('ess', 'cum1', 'ne'), None],
    [('ess', 'cum2', 'uss'), None],
    [('ess', 'cum2', 'ne'), None],
    [('ess', 'ro1', 'uss'), None],
    [('ess', 'ro1', 'ne'), None],
    [('ess', 'ro2', 'uss'), None],
    [('ess', 'ro2', 'ne'), None],
    [('fo', 'cum1', 'uss'), None],
    [('fo', 'cum1', 'ne'), None],
    [('fo', 'cum2', 'uss'), None],
    [('fo', 'cum2', 'ne'), None],
    [('fo', 'ro1', 'uss'), None],
    [('fo', 'ro1', 'ne'), None],
    [('fo', 'ro2', 'uss'), None],
    [('fo', 'ro2', 'ne'), None],
    [('inde', 'cum1', 'uss'), None],
    [('inde', 'cum1', 'ne'), None],
    [('inde', 'cum2', 'uss'), None],
    [('inde', 'cum2', 'ne'), None],
    [('inde', 'ro1', 'uss'), None],
    [('inde', 'ro1', 'ne'), None],
    [('inde', 'ro2', 'uss'), None],
    [('inde', 'ro2', 'ne'), None],
    [('ad1', 'cum1', 'uss'), None],
    [('ad1', 'cum1', 'ne'), None],
    [('ad1', 'cum2', 'uss'), None],
    [('ad1', 'cum2', 'ne'), None],
    [('ad1', 'ro1', 'uss'), None],
    [('ad1', 'ro1', 'ne'), None],
    [('ad1', 'ro2', 'uss'), None],
    [('ad1', 'ro2', 'ne'), None],
    [('ad2', 'cum1', 'uss'), None],
    [('ad2', 'cum1', 'ne'), None],
    [('ad2', 'cum2', 'uss'), None],
    [('ad2', 'cum2', 'ne'), None],
    [('ad2', 'ro1', 'uss'), None],
    [('ad2', 'ro1', 'ne'), None],
    [('ad2', 'ro2', 'uss'), None],
    [('ad2', 'ro2', 'ne'), None],
    [('athe', 'cum1', 'uss'), None],
    [('athe', 'cum1', 'ne'), None],
    [('athe', 'cum2', 'uss'), None],
    [('athe', 'cum2', 'ne'), None],
    [('athe', 'ro1', 'uss'), None],
    [('athe', 'ro1', 'ne'), None],
    [('athe', 'ro2', 'uss'), None],
    [('athe', 'ro2', 'ne'), None],
    [('are', 'cum1', 'uss'), None],
    [('are', 'cum1', 'ne'), None],
    [('are', 'cum2', 'uss'), None],
    [('are', 'cum2', 'ne'), None],
    [('are', 'ro1', 'uss'), None],
    [('are', 'ro1', 'ne'), None],
    [('are', 'ro2', 'uss'), None],
    [('are', 'ro2', 'ne'), None],
    [('de', 'cum1', 'uss'), None],
    [('de', 'cum1', 'ne'), None],
    [('de', 'cum2', 'uss'), None],
    [('de', 'cum2', 'ne'), None],
    [('de', 'ro1', 'uss'), None],
    [('de', 'ro1', 'ne'), None],
    [('de', 'ro2', 'uss'), None],
    [('de', 'ro2', 'ne'), None],
    [('to', 'for', 'ad1', 'cum1'), None],
    [('to', 'for', 'ad1', 'cum2'), None],
    [('to', 'for', 'ad1', 'ro1'), None],
    [('to', 'for', 'ad1', 'ro2'), None],
    [('to', 'for', 'ad2', 'cum1'), None],
    [('to', 'for', 'ad2', 'cum2'), None],
    [('to', 'for', 'ad2', 'ro1'), None],
    [('to', 'for', 'ad2', 'ro2'), None],
    [('to', 'for', 'athe', 'cum1'), None],
    [('to', 'for', 'athe', 'cum2'), None],
    [('to', 'for', 'athe', 'ro1'), None],
    [('to', 'for', 'athe', 'ro2'), None],
    [('to', 'for', 'are', 'cum1'), None],
    [('to', 'for', 'are', 'cum2'), None],
    [('to', 'for', 'are', 'ro1'), None],
    [('to', 'for', 'are', 'ro2'), None],
    [('to', 'for', 'de', 'cum1'), None],
    [('to', 'for', 'de', 'cum2'), None],
    [('to', 'for', 'de', 'ro1'), None],
    [('to', 'for', 'de', 'ro2'), None],
    [('to', 'fris', 'ad1', 'cum1'), None],
    [('to', 'fris', 'ad1', 'cum2'), None],
    [('to', 'fris', 'ad1', 'ro1'), None],
    [('to', 'fris', 'ad1', 'ro2'), None],
    [('to', 'fris', 'ad2', 'cum1'), None],
    [('to', 'fris', 'ad2', 'cum2'), None],
    [('to', 'fris', 'ad2', 'ro1'), None],
    [('to', 'fris', 'ad2', 'ro2'), None],
    [('to', 'fris', 'athe', 'cum1'), None],
    [('to', 'fris', 'athe', 'cum2'), None],
    [('to', 'fris', 'athe', 'ro1'), None],
    [('to', 'fris', 'athe', 'ro2'), None],
    [('to', 'fris', 'are', 'cum1'), None],
    [('to', 'fris', 'are', 'cum2'), None],
    [('to', 'fris', 'are', 'ro1'), None],
    [('to', 'fris', 'are', 'ro2'), None],
    [('to', 'fris', 'de', 'cum1'), None],
    [('to', 'fris', 'de', 'cum2'), None],
    [('to', 'fris', 'de', 'ro1'), None],
    [('to', 'fris', 'de', 'ro2'), None],
    [('to', 'eter', 'ad1', 'cum1'), None],
    [('to', 'eter', 'ad1', 'cum2'), None],
    [('to', 'eter', 'ad1', 'ro1'), None],
    [('to', 'eter', 'ad1', 'ro2'), None],
    [('to', 'eter', 'ad2', 'cum1'), None],
    [('to', 'eter', 'ad2', 'cum2'), None],
    [('to', 'eter', 'ad2', 'ro1'), None],
    [('to', 'eter', 'ad2', 'ro2'), None],
    [('to', 'eter', 'athe', 'cum1'), None],
    [('to', 'eter', 'athe', 'cum2'), None],
    [('to', 'eter', 'athe', 'ro1'), None],
    [('to', 'eter', 'athe', 'ro2'), None],
    [('to', 'eter', 'are', 'cum1'), None],
    [('to', 'eter', 'are', 'cum2'), None],
    [('to', 'eter', 'are', 'ro1'), None],
    [('to', 'eter', 'are', 'ro2'), None],
    [('to', 'eter', 'de', 'cum1'), None],
    [('to', 'eter', 'de', 'cum2'), None],
    [('to', 'eter', 'de', 'ro1'), None],
    [('to', 'eter', 'de', 'ro2'), None],
    [('to', 'imbe', 'ad1', 'cum1'), None],
    [('to', 'imbe', 'ad1', 'cum2'), None],
    [('to', 'imbe', 'ad1', 'ro1'), None],
    [('to', 'imbe', 'ad1', 'ro2'), None],
    [('to', 'imbe', 'ad2', 'cum1'), None],
    [('to', 'imbe', 'ad2', 'cum2'), None],
    [('to', 'imbe', 'ad2', 'ro1'), None],
    [('to', 'imbe', 'ad2', 'ro2'), None],
    [('to', 'imbe', 'athe', 'cum1'), None],
    [('to', 'imbe', 'athe', 'cum2'), None],
    [('to', 'imbe', 'athe', 'ro1'), None],
    [('to', 'imbe', 'athe', 'ro2'), None],
    [('to', 'imbe', 'are', 'cum1'), None],
    [('to', 'imbe', 'are', 'cum2'), None],
    [('to', 'imbe', 'are', 'ro1'), None],
    [('to', 'imbe', 'are', 'ro2'), None],
    [('to', 'imbe', 'de', 'cum1'), None],
    [('to', 'imbe', 'de', 'cum2'), None],
    [('to', 'imbe', 'de', 'ro1'), None],
    [('to', 'imbe', 'de', 'ro2'), None],
    [('to', 'ess', 'ad1', 'cum1'), None],
    [('to', 'ess', 'ad1', 'cum2'), None],
    [('to', 'ess', 'ad1', 'ro1'), None],
    [('to', 'ess', 'ad1', 'ro2'), None],
    [('to', 'ess', 'ad2', 'cum1'), None],
    [('to', 'ess', 'ad2', 'cum2'), None],
    [('to', 'ess', 'ad2', 'ro1'), None],
    [('to', 'ess', 'ad2', 'ro2'), None],
    [('to', 'ess', 'athe', 'cum1'), None],
    [('to', 'ess', 'athe', 'cum2'), None],
    [('to', 'ess', 'athe', 'ro1'), None],
    [('to', 'ess', 'athe', 'ro2'), None],
    [('to', 'ess', 'are', 'cum1'), None],
    [('to', 'ess', 'are', 'cum2'), None],
    [('to', 'ess', 'are', 'ro1'), None],
    [('to', 'ess', 'are', 'ro2'), None],
    [('to', 'ess', 'de', 'cum1'), None],
    [('to', 'ess', 'de', 'cum2'), None],
    [('to', 'ess', 'de', 'ro1'), None],
    [('to', 'ess', 'de', 'ro2'), None],
    [('to', 'fo', 'ad1', 'cum1'), None],
    [('to', 'fo', 'ad1', 'cum2'), None],
    [('to', 'fo', 'ad1', 'ro1'), None],
    [('to', 'fo', 'ad1', 'ro2'), None],
    [('to', 'fo', 'ad2', 'cum1'), None],
    [('to', 'fo', 'ad2', 'cum2'), None],
    [('to', 'fo', 'ad2', 'ro1'), None],
    [('to', 'fo', 'ad2', 'ro2'), None],
    [('to', 'fo', 'athe', 'cum1'), None],
    [('to', 'fo', 'athe', 'cum2'), None],
    [('to', 'fo', 'athe', 'ro1'), None],
    [('to', 'fo', 'athe', 'ro2'), None],
    [('to', 'fo', 'are', 'cum1'), None],
    [('to', 'fo', 'are', 'cum2'), None],
    [('to', 'fo', 'are', 'ro1'), None],
    [('to', 'fo', 'are', 'ro2'), None],
    [('to', 'fo', 'de', 'cum1'), None],
    [('to', 'fo', 'de', 'cum2'), None],
    [('to', 'fo', 'de', 'ro1'), None],
    [('to', 'fo', 'de', 'ro2'), None],
    [('to', 'inde', 'ad1', 'cum1'), None],
    [('to', 'inde', 'ad1', 'cum2'), None],
    [('to', 'inde', 'ad1', 'ro1'), None],
    [('to', 'inde', 'ad1', 'ro2'), None],
    [('to', 'inde', 'ad2', 'cum1'), None],
    [('to', 'inde', 'ad2', 'cum2'), None],
    [('to', 'inde', 'ad2', 'ro1'), None],
    [('to', 'inde', 'ad2', 'ro2'), None],
    [('to', 'inde', 'athe', 'cum1'), None],
    [('to', 'inde', 'athe', 'cum2'), None],
    [('to', 'inde', 'athe', 'ro1'), None],
    [('to', 'inde', 'athe', 'ro2'), None],
    [('to', 'inde', 'are', 'cum1'), None],
    [('to', 'inde', 'are', 'cum2'), None],
    [('to', 'inde', 'are', 'ro1'), None],
    [('to', 'inde', 'are', 'ro2'), None],
    [('to', 'inde', 'de', 'cum1'), None],
    [('to', 'inde', 'de', 'cum2'), None],
    [('to', 'inde', 'de', 'ro1'), None],
    [('to', 'inde', 'de', 'ro2'), None],
    [('to', 'for', 'ad1', 'uss'), None],
    [('to', 'for', 'ad1', 'ne'), None],
    [('to', 'for', 'ad2', 'uss'), None],
    [('to', 'for', 'ad2', 'ne'), None],
    [('to', 'for', 'athe', 'uss'), None],
    [('to', 'for', 'athe', 'ne'), None],
    [('to', 'for', 'are', 'uss'), None],
    [('to', 'for', 'are', 'ne'), None],
    [('to', 'for', 'de', 'uss'), None],
    [('to', 'for', 'de', 'ne'), None],
    [('to', 'fris', 'ad1', 'uss'), None],
    [('to', 'fris', 'ad1', 'ne'), None],
    [('to', 'fris', 'ad2', 'uss'), None],
    [('to', 'fris', 'ad2', 'ne'), None],
    [('to', 'fris', 'athe', 'uss'), None],
    [('to', 'fris', 'athe', 'ne'), None],
    [('to', 'fris', 'are', 'uss'), None],
    [('to', 'fris', 'are', 'ne'), None],
    [('to', 'fris', 'de', 'uss'), None],
    [('to', 'fris', 'de', 'ne'), None],
    [('to', 'eter', 'ad1', 'uss'), None],
    [('to', 'eter', 'ad1', 'ne'), None],
    [('to', 'eter', 'ad2', 'uss'), None],
    [('to', 'eter', 'ad2', 'ne'), None],
    [('to', 'eter', 'athe', 'uss'), None],
    [('to', 'eter', 'athe', 'ne'), None],
    [('to', 'eter', 'are', 'uss'), None],
    [('to', 'eter', 'are', 'ne'), None],
    [('to', 'eter', 'de', 'uss'), None],
    [('to', 'eter', 'de', 'ne'), None],
    [('to', 'imbe', 'ad1', 'uss'), None],
    [('to', 'imbe', 'ad1', 'ne'), None],
    [('to', 'imbe', 'ad2', 'uss'), None],
    [('to', 'imbe', 'ad2', 'ne'), None],
    [('to', 'imbe', 'athe', 'uss'), None],
    [('to', 'imbe', 'athe', 'ne'), None],
    [('to', 'imbe', 'are', 'uss'), None],
    [('to', 'imbe', 'are', 'ne'), None],
    [('to', 'imbe', 'de', 'uss'), None],
    [('to', 'imbe', 'de', 'ne'), None],
    [('to', 'ess', 'ad1', 'uss'), None],
    [('to', 'ess', 'ad1', 'ne'), None],
    [('to', 'ess', 'ad2', 'uss'), None],
    [('to', 'ess', 'ad2', 'ne'), None],
    [('to', 'ess', 'athe', 'uss'), None],
    [('to', 'ess', 'athe', 'ne'), None],
    [('to', 'ess', 'are', 'uss'), None],
    [('to', 'ess', 'are', 'ne'), None],
    [('to', 'ess', 'de', 'uss'), None],
    [('to', 'ess', 'de', 'ne'), None],
    [('to', 'fo', 'ad1', 'uss'), None],
    [('to', 'fo', 'ad1', 'ne'), None],
    [('to', 'fo', 'ad2', 'uss'), None],
    [('to', 'fo', 'ad2', 'ne'), None],
    [('to', 'fo', 'athe', 'uss'), None],
    [('to', 'fo', 'athe', 'ne'), None],
    [('to', 'fo', 'are', 'uss'), None],
    [('to', 'fo', 'are', 'ne'), None],
    [('to', 'fo', 'de', 'uss'), None],
    [('to', 'fo', 'de', 'ne'), None],
    [('to', 'inde', 'ad1', 'uss'), None],
    [('to', 'inde', 'ad1', 'ne'), None],
    [('to', 'inde', 'ad2', 'uss'), None],
    [('to', 'inde', 'ad2', 'ne'), None],
    [('to', 'inde', 'athe', 'uss'), None],
    [('to', 'inde', 'athe', 'ne'), None],
    [('to', 'inde', 'are', 'uss'), None],
    [('to', 'inde', 'are', 'ne'), None],
    [('to', 'inde', 'de', 'uss'), None],
    [('to', 'inde', 'de', 'ne'), None],
    [('to', 'for', 'cum1', 'uss'), None],
    [('to', 'for', 'cum1', 'ne'), None],
    [('to', 'for', 'cum2', 'uss'), None],
    [('to', 'for', 'cum2', 'ne'), None],
    [('to', 'for', 'ro1', 'uss'), None],
    [('to', 'for', 'ro1', 'ne'), None],
    [('to', 'for', 'ro2', 'uss'), None],
    [('to', 'for', 'ro2', 'ne'), None],
    [('to', 'fris', 'cum1', 'uss'), None],
    [('to', 'fris', 'cum1', 'ne'), None],
    [('to', 'fris', 'cum2', 'uss'), None],
    [('to', 'fris', 'cum2', 'ne'), None],
    [('to', 'fris', 'ro1', 'uss'), None],
    [('to', 'fris', 'ro1', 'ne'), None],
    [('to', 'fris', 'ro2', 'uss'), None],
    [('to', 'fris', 'ro2', 'ne'), None],
    [('to', 'eter', 'cum1', 'uss'), None],
    [('to', 'eter', 'cum1', 'ne'), None],
    [('to', 'eter', 'cum2', 'uss'), None],
    [('to', 'eter', 'cum2', 'ne'), None],
    [('to', 'eter', 'ro1', 'uss'), None],
    [('to', 'eter', 'ro1', 'ne'), None],
    [('to', 'eter', 'ro2', 'uss'), None],
    [('to', 'eter', 'ro2', 'ne'), None],
    [('to', 'imbe', 'cum1', 'uss'), None],
    [('to', 'imbe', 'cum1', 'ne'), None],
    [('to', 'imbe', 'cum2', 'uss'), None],
    [('to', 'imbe', 'cum2', 'ne'), None],
    [('to', 'imbe', 'ro1', 'uss'), None],
    [('to', 'imbe', 'ro1', 'ne'), None],
    [('to', 'imbe', 'ro2', 'uss'), None],
    [('to', 'imbe', 'ro2', 'ne'), None],
    [('to', 'ess', 'cum1', 'uss'), None],
    [('to', 'ess', 'cum1', 'ne'), None],
    [('to', 'ess', 'cum2', 'uss'), None],
    [('to', 'ess', 'cum2', 'ne'), None],
    [('to', 'ess', 'ro1', 'uss'), None],
    [('to', 'ess', 'ro1', 'ne'), None],
    [('to', 'ess', 'ro2', 'uss'), None],
    [('to', 'ess', 'ro2', 'ne'), None],
    [('to', 'fo', 'cum1', 'uss'), None],
    [('to', 'fo', 'cum1', 'ne'), None],
    [('to', 'fo', 'cum2', 'uss'), None],
    [('to', 'fo', 'cum2', 'ne'), None],
    [('to', 'fo', 'ro1', 'uss'), None],
    [('to', 'fo', 'ro1', 'ne'), None],
    [('to', 'fo', 'ro2', 'uss'), None],
    [('to', 'fo', 'ro2', 'ne'), None],
    [('to', 'inde', 'cum1', 'uss'), None],
    [('to', 'inde', 'cum1', 'ne'), None],
    [('to', 'inde', 'cum2', 'uss'), None],
    [('to', 'inde', 'cum2', 'ne'), None],
    [('to', 'inde', 'ro1', 'uss'), None],
    [('to', 'inde', 'ro1', 'ne'), None],
    [('to', 'inde', 'ro2', 'uss'), None],
    [('to', 'inde', 'ro2', 'ne'), None],
    [('to', 'ad1', 'cum1', 'uss'), None],
    [('to', 'ad1', 'cum1', 'ne'), None],
    [('to', 'ad1', 'cum2', 'uss'), None],
    [('to', 'ad1', 'cum2', 'ne'), None],
    [('to', 'ad1', 'ro1', 'uss'), None],
    [('to', 'ad1', 'ro1', 'ne'), None],
    [('to', 'ad1', 'ro2', 'uss'), None],
    [('to', 'ad1', 'ro2', 'ne'), None],
    [('to', 'ad2', 'cum1', 'uss'), None],
    [('to', 'ad2', 'cum1', 'ne'), None],
    [('to', 'ad2', 'cum2', 'uss'), None],
    [('to', 'ad2', 'cum2', 'ne'), None],
    [('to', 'ad2', 'ro1', 'uss'), None],
    [('to', 'ad2', 'ro1', 'ne'), None],
    [('to', 'ad2', 'ro2', 'uss'), None],
    [('to', 'ad2', 'ro2', 'ne'), None],
    [('to', 'athe', 'cum1', 'uss'), None],
    [('to', 'athe', 'cum1', 'ne'), None],
    [('to', 'athe', 'cum2', 'uss'), None],
    [('to', 'athe', 'cum2', 'ne'), None],
    [('to', 'athe', 'ro1', 'uss'), None],
    [('to', 'athe', 'ro1', 'ne'), None],
    [('to', 'athe', 'ro2', 'uss'), None],
    [('to', 'athe', 'ro2', 'ne'), None],
    [('to', 'are', 'cum1', 'uss'), None],
    [('to', 'are', 'cum1', 'ne'), None],
    [('to', 'are', 'cum2', 'uss'), None],
    [('to', 'are', 'cum2', 'ne'), None],
    [('to', 'are', 'ro1', 'uss'), None],
    [('to', 'are', 'ro1', 'ne'), None],
    [('to', 'are', 'ro2', 'uss'), None],
    [('to', 'are', 'ro2', 'ne'), None],
    [('to', 'de', 'cum1', 'uss'), None],
    [('to', 'de', 'cum1', 'ne'), None],
    [('to', 'de', 'cum2', 'uss'), None],
    [('to', 'de', 'cum2', 'ne'), None],
    [('to', 'de', 'ro1', 'uss'), None],
    [('to', 'de', 'ro1', 'ne'), None],
    [('to', 'de', 'ro2', 'uss'), None],
    [('to', 'de', 'ro2', 'ne'), None],
    [('for', 'ad1', 'cum1', 'uss'), None],
    [('for', 'ad1', 'cum1', 'ne'), None],
    [('for', 'ad1', 'cum2', 'uss'), None],
    [('for', 'ad1', 'cum2', 'ne'), None],
    [('for', 'ad1', 'ro1', 'uss'), None],
    [('for', 'ad1', 'ro1', 'ne'), None],
    [('for', 'ad1', 'ro2', 'uss'), None],
    [('for', 'ad1', 'ro2', 'ne'), None],
    [('for', 'ad2', 'cum1', 'uss'), None],
    [('for', 'ad2', 'cum1', 'ne'), None],
    [('for', 'ad2', 'cum2', 'uss'), None],
    [('for', 'ad2', 'cum2', 'ne'), None],
    [('for', 'ad2', 'ro1', 'uss'), None],
    [('for', 'ad2', 'ro1', 'ne'), None],
    [('for', 'ad2', 'ro2', 'uss'), None],
    [('for', 'ad2', 'ro2', 'ne'), None],
    [('for', 'athe', 'cum1', 'uss'), None],
    [('for', 'athe', 'cum1', 'ne'), None],
    [('for', 'athe', 'cum2', 'uss'), None],
    [('for', 'athe', 'cum2', 'ne'), None],
    [('for', 'athe', 'ro1', 'uss'), None],
    [('for', 'athe', 'ro1', 'ne'), None],
    [('for', 'athe', 'ro2', 'uss'), None],
    [('for', 'athe', 'ro2', 'ne'), None],
    [('for', 'are', 'cum1', 'uss'), None],
    [('for', 'are', 'cum1', 'ne'), None],
    [('for', 'are', 'cum2', 'uss'), None],
    [('for', 'are', 'cum2', 'ne'), None],
    [('for', 'are', 'ro1', 'uss'), None],
    [('for', 'are', 'ro1', 'ne'), None],
    [('for', 'are', 'ro2', 'uss'), None],
    [('for', 'are', 'ro2', 'ne'), None],
    [('for', 'de', 'cum1', 'uss'), None],
    [('for', 'de', 'cum1', 'ne'), None],
    [('for', 'de', 'cum2', 'uss'), None],
    [('for', 'de', 'cum2', 'ne'), None],
    [('for', 'de', 'ro1', 'uss'), None],
    [('for', 'de', 'ro1', 'ne'), None],
    [('for', 'de', 'ro2', 'uss'), None],
    [('for', 'de', 'ro2', 'ne'), None],
    [('fris', 'ad1', 'cum1', 'uss'), None],
    [('fris', 'ad1', 'cum1', 'ne'), None],
    [('fris', 'ad1', 'cum2', 'uss'), None],
    [('fris', 'ad1', 'cum2', 'ne'), None],
    [('fris', 'ad1', 'ro1', 'uss'), None],
    [('fris', 'ad1', 'ro1', 'ne'), None],
    [('fris', 'ad1', 'ro2', 'uss'), None],
    [('fris', 'ad1', 'ro2', 'ne'), None],
    [('fris', 'ad2', 'cum1', 'uss'), None],
    [('fris', 'ad2', 'cum1', 'ne'), None],
    [('fris', 'ad2', 'cum2', 'uss'), None],
    [('fris', 'ad2', 'cum2', 'ne'), None],
    [('fris', 'ad2', 'ro1', 'uss'), None],
    [('fris', 'ad2', 'ro1', 'ne'), None],
    [('fris', 'ad2', 'ro2', 'uss'), None],
    [('fris', 'ad2', 'ro2', 'ne'), None],
    [('fris', 'athe', 'cum1', 'uss'), None],
    [('fris', 'athe', 'cum1', 'ne'), None],
    [('fris', 'athe', 'cum2', 'uss'), None],
    [('fris', 'athe', 'cum2', 'ne'), None],
    [('fris', 'athe', 'ro1', 'uss'), None],
    [('fris', 'athe', 'ro1', 'ne'), None],
    [('fris', 'athe', 'ro2', 'uss'), None],
    [('fris', 'athe', 'ro2', 'ne'), None],
    [('fris', 'are', 'cum1', 'uss'), None],
    [('fris', 'are', 'cum1', 'ne'), None],
    [('fris', 'are', 'cum2', 'uss'), None],
    [('fris', 'are', 'cum2', 'ne'), None],
    [('fris', 'are', 'ro1', 'uss'), None],
    [('fris', 'are', 'ro1', 'ne'), None],
    [('fris', 'are', 'ro2', 'uss'), None],
    [('fris', 'are', 'ro2', 'ne'), None],
    [('fris', 'de', 'cum1', 'uss'), None],
    [('fris', 'de', 'cum1', 'ne'), None],
    [('fris', 'de', 'cum2', 'uss'), None],
    [('fris', 'de', 'cum2', 'ne'), None],
    [('fris', 'de', 'ro1', 'uss'), None],
    [('fris', 'de', 'ro1', 'ne'), None],
    [('fris', 'de', 'ro2', 'uss'), None],
    [('fris', 'de', 'ro2', 'ne'), None],
    [('eter', 'ad1', 'cum1', 'uss'), None],
    [('eter', 'ad1', 'cum1', 'ne'), None],
    [('eter', 'ad1', 'cum2', 'uss'), None],
    [('eter', 'ad1', 'cum2', 'ne'), None],
    [('eter', 'ad1', 'ro1', 'uss'), None],
    [('eter', 'ad1', 'ro1', 'ne'), None],
    [('eter', 'ad1', 'ro2', 'uss'), None],
    [('eter', 'ad1', 'ro2', 'ne'), None],
    [('eter', 'ad2', 'cum1', 'uss'), None],
    [('eter', 'ad2', 'cum1', 'ne'), None],
    [('eter', 'ad2', 'cum2', 'uss'), None],
    [('eter', 'ad2', 'cum2', 'ne'), None],
    [('eter', 'ad2', 'ro1', 'uss'), None],
    [('eter', 'ad2', 'ro1', 'ne'), None],
    [('eter', 'ad2', 'ro2', 'uss'), None],
    [('eter', 'ad2', 'ro2', 'ne'), None],
    [('eter', 'athe', 'cum1', 'uss'), None],
    [('eter', 'athe', 'cum1', 'ne'), None],
    [('eter', 'athe', 'cum2', 'uss'), None],
    [('eter', 'athe', 'cum2', 'ne'), None],
    [('eter', 'athe', 'ro1', 'uss'), None],
    [('eter', 'athe', 'ro1', 'ne'), None],
    [('eter', 'athe', 'ro2', 'uss'), None],
    [('eter', 'athe', 'ro2', 'ne'), None],
    [('eter', 'are', 'cum1', 'uss'), None],
    [('eter', 'are', 'cum1', 'ne'), None],
    [('eter', 'are', 'cum2', 'uss'), None],
    [('eter', 'are', 'cum2', 'ne'), None],
    [('eter', 'are', 'ro1', 'uss'), None],
    [('eter', 'are', 'ro1', 'ne'), None],
    [('eter', 'are', 'ro2', 'uss'), None],
    [('eter', 'are', 'ro2', 'ne'), None],
    [('eter', 'de', 'cum1', 'uss'), None],
    [('eter', 'de', 'cum1', 'ne'), None],
    [('eter', 'de', 'cum2', 'uss'), None],
    [('eter', 'de', 'cum2', 'ne'), None],
    [('eter', 'de', 'ro1', 'uss'), None],
    [('eter', 'de', 'ro1', 'ne'), None],
    [('eter', 'de', 'ro2', 'uss'), None],
    [('eter', 'de', 'ro2', 'ne'), None],
    [('imbe', 'ad1', 'cum1', 'uss'), None],
    [('imbe', 'ad1', 'cum1', 'ne'), None],
    [('imbe', 'ad1', 'cum2', 'uss'), None],
    [('imbe', 'ad1', 'cum2', 'ne'), None],
    [('imbe', 'ad1', 'ro1', 'uss'), None],
    [('imbe', 'ad1', 'ro1', 'ne'), None],
    [('imbe', 'ad1', 'ro2', 'uss'), None],
    [('imbe', 'ad1', 'ro2', 'ne'), None],
    [('imbe', 'ad2', 'cum1', 'uss'), None],
    [('imbe', 'ad2', 'cum1', 'ne'), None],
    [('imbe', 'ad2', 'cum2', 'uss'), None],
    [('imbe', 'ad2', 'cum2', 'ne'), None],
    [('imbe', 'ad2', 'ro1', 'uss'), None],
    [('imbe', 'ad2', 'ro1', 'ne'), None],
    [('imbe', 'ad2', 'ro2', 'uss'), None],
    [('imbe', 'ad2', 'ro2', 'ne'), None],
    [('imbe', 'athe', 'cum1', 'uss'), None],
    [('imbe', 'athe', 'cum1', 'ne'), None],
    [('imbe', 'athe', 'cum2', 'uss'), None],
    [('imbe', 'athe', 'cum2', 'ne'), None],
    [('imbe', 'athe', 'ro1', 'uss'), None],
    [('imbe', 'athe', 'ro1', 'ne'), None],
    [('imbe', 'athe', 'ro2', 'uss'), None],
    [('imbe', 'athe', 'ro2', 'ne'), None],
    [('imbe', 'are', 'cum1', 'uss'), None],
    [('imbe', 'are', 'cum1', 'ne'), None],
    [('imbe', 'are', 'cum2', 'uss'), None],
    [('imbe', 'are', 'cum2', 'ne'), None],
    [('imbe', 'are', 'ro1', 'uss'), None],
    [('imbe', 'are', 'ro1', 'ne'), None],
    [('imbe', 'are', 'ro2', 'uss'), None],
    [('imbe', 'are', 'ro2', 'ne'), None],
    [('imbe', 'de', 'cum1', 'uss'), None],
    [('imbe', 'de', 'cum1', 'ne'), None],
    [('imbe', 'de', 'cum2', 'uss'), None],
    [('imbe', 'de', 'cum2', 'ne'), None],
    [('imbe', 'de', 'ro1', 'uss'), None],
    [('imbe', 'de', 'ro1', 'ne'), None],
    [('imbe', 'de', 'ro2', 'uss'), None],
    [('imbe', 'de', 'ro2', 'ne'), None],
    [('ess', 'ad1', 'cum1', 'uss'), None],
    [('ess', 'ad1', 'cum1', 'ne'), None],
    [('ess', 'ad1', 'cum2', 'uss'), None],
    [('ess', 'ad1', 'cum2', 'ne'), None],
    [('ess', 'ad1', 'ro1', 'uss'), None],
    [('ess', 'ad1', 'ro1', 'ne'), None],
    [('ess', 'ad1', 'ro2', 'uss'), None],
    [('ess', 'ad1', 'ro2', 'ne'), None],
    [('ess', 'ad2', 'cum1', 'uss'), None],
    [('ess', 'ad2', 'cum1', 'ne'), None],
    [('ess', 'ad2', 'cum2', 'uss'), None],
    [('ess', 'ad2', 'cum2', 'ne'), None],
    [('ess', 'ad2', 'ro1', 'uss'), None],
    [('ess', 'ad2', 'ro1', 'ne'), None],
    [('ess', 'ad2', 'ro2', 'uss'), None],
    [('ess', 'ad2', 'ro2', 'ne'), None],
    [('ess', 'athe', 'cum1', 'uss'), None],
    [('ess', 'athe', 'cum1', 'ne'), None],
    [('ess', 'athe', 'cum2', 'uss'), None],
    [('ess', 'athe', 'cum2', 'ne'), None],
    [('ess', 'athe', 'ro1', 'uss'), None],
    [('ess', 'athe', 'ro1', 'ne'), None],
    [('ess', 'athe', 'ro2', 'uss'), None],
    [('ess', 'athe', 'ro2', 'ne'), None],
    [('ess', 'are', 'cum1', 'uss'), None],
    [('ess', 'are', 'cum1', 'ne'), None],
    [('ess', 'are', 'cum2', 'uss'), None],
    [('ess', 'are', 'cum2', 'ne'), None],
    [('ess', 'are', 'ro1', 'uss'), None],
    [('ess', 'are', 'ro1', 'ne'), None],
    [('ess', 'are', 'ro2', 'uss'), None],
    [('ess', 'are', 'ro2', 'ne'), None],
    [('ess', 'de', 'cum1', 'uss'), None],
    [('ess', 'de', 'cum1', 'ne'), None],
    [('ess', 'de', 'cum2', 'uss'), None],
    [('ess', 'de', 'cum2', 'ne'), None],
    [('ess', 'de', 'ro1', 'uss'), None],
    [('ess', 'de', 'ro1', 'ne'), None],
    [('ess', 'de', 'ro2', 'uss'), None],
    [('ess', 'de', 'ro2', 'ne'), None],
    [('fo', 'ad1', 'cum1', 'uss'), None],
    [('fo', 'ad1', 'cum1', 'ne'), None],
    [('fo', 'ad1', 'cum2', 'uss'), None],
    [('fo', 'ad1', 'cum2', 'ne'), None],
    [('fo', 'ad1', 'ro1', 'uss'), None],
    [('fo', 'ad1', 'ro1', 'ne'), None],
    [('fo', 'ad1', 'ro2', 'uss'), None],
    [('fo', 'ad1', 'ro2', 'ne'), None],
    [('fo', 'ad2', 'cum1', 'uss'), None],
    [('fo', 'ad2', 'cum1', 'ne'), None],
    [('fo', 'ad2', 'cum2', 'uss'), None],
    [('fo', 'ad2', 'cum2', 'ne'), None],
    [('fo', 'ad2', 'ro1', 'uss'), None],
    [('fo', 'ad2', 'ro1', 'ne'), None],
    [('fo', 'ad2', 'ro2', 'uss'), None],
    [('fo', 'ad2', 'ro2', 'ne'), None],
    [('fo', 'athe', 'cum1', 'uss'), None],
    [('fo', 'athe', 'cum1', 'ne'), None],
    [('fo', 'athe', 'cum2', 'uss'), None],
    [('fo', 'athe', 'cum2', 'ne'), None],
    [('fo', 'athe', 'ro1', 'uss'), None],
    [('fo', 'athe', 'ro1', 'ne'), None],
    [('fo', 'athe', 'ro2', 'uss'), None],
    [('fo', 'athe', 'ro2', 'ne'), None],
    [('fo', 'are', 'cum1', 'uss'), None],
    [('fo', 'are', 'cum1', 'ne'), None],
    [('fo', 'are', 'cum2', 'uss'), None],
    [('fo', 'are', 'cum2', 'ne'), None],
    [('fo', 'are', 'ro1', 'uss'), None],
    [('fo', 'are', 'ro1', 'ne'), None],
    [('fo', 'are', 'ro2', 'uss'), None],
    [('fo', 'are', 'ro2', 'ne'), None],
    [('fo', 'de', 'cum1', 'uss'), None],
    [('fo', 'de', 'cum1', 'ne'), None],
    [('fo', 'de', 'cum2', 'uss'), None],
    [('fo', 'de', 'cum2', 'ne'), None],
    [('fo', 'de', 'ro1', 'uss'), None],
    [('fo', 'de', 'ro1', 'ne'), None],
    [('fo', 'de', 'ro2', 'uss'), None],
    [('fo', 'de', 'ro2', 'ne'), None],
    [('inde', 'ad1', 'cum1', 'uss'), None],
    [('inde', 'ad1', 'cum1', 'ne'), None],
    [('inde', 'ad1', 'cum2', 'uss'), None],
    [('inde', 'ad1', 'cum2', 'ne'), None],
    [('inde', 'ad1', 'ro1', 'uss'), None],
    [('inde', 'ad1', 'ro1', 'ne'), None],
    [('inde', 'ad1', 'ro2', 'uss'), None],
    [('inde', 'ad1', 'ro2', 'ne'), None],
    [('inde', 'ad2', 'cum1', 'uss'), None],
    [('inde', 'ad2', 'cum1', 'ne'), None],
    [('inde', 'ad2', 'cum2', 'uss'), None],
    [('inde', 'ad2', 'cum2', 'ne'), None],
    [('inde', 'ad2', 'ro1', 'uss'), None],
    [('inde', 'ad2', 'ro1', 'ne'), None],
    [('inde', 'ad2', 'ro2', 'uss'), None],
    [('inde', 'ad2', 'ro2', 'ne'), None],
    [('inde', 'athe', 'cum1', 'uss'), None],
    [('inde', 'athe', 'cum1', 'ne'), None],
    [('inde', 'athe', 'cum2', 'uss'), None],
    [('inde', 'athe', 'cum2', 'ne'), None],
    [('inde', 'athe', 'ro1', 'uss'), None],
    [('inde', 'athe', 'ro1', 'ne'), None],
    [('inde', 'athe', 'ro2', 'uss'), None],
    [('inde', 'athe', 'ro2', 'ne'), None],
    [('inde', 'are', 'cum1', 'uss'), None],
    [('inde', 'are', 'cum1', 'ne'), None],
    [('inde', 'are', 'cum2', 'uss'), None],
    [('inde', 'are', 'cum2', 'ne'), None],
    [('inde', 'are', 'ro1', 'uss'), None],
    [('inde', 'are', 'ro1', 'ne'), None],
    [('inde', 'are', 'ro2', 'uss'), None],
    [('inde', 'are', 'ro2', 'ne'), None],
    [('inde', 'de', 'cum1', 'uss'), None],
    [('inde', 'de', 'cum1', 'ne'), None],
    [('inde', 'de', 'cum2', 'uss'), None],
    [('inde', 'de', 'cum2', 'ne'), None],
    [('inde', 'de', 'ro1', 'uss'), None],
    [('inde', 'de', 'ro1', 'ne'), None],
    [('inde', 'de', 'ro2', 'uss'), None],
    [('inde', 'de', 'ro2', 'ne'), None],
    [('to', 'for', 'ad1', 'cum1', 'uss'), None],
    [('to', 'for', 'ad1', 'cum1', 'ne'), None],
    [('to', 'for', 'ad1', 'cum2', 'uss'), None],
    [('to', 'for', 'ad1', 'cum2', 'ne'), None],
    [('to', 'for', 'ad1', 'ro1', 'uss'), None],
    [('to', 'for', 'ad1', 'ro1', 'ne'), None],
    [('to', 'for', 'ad1', 'ro2', 'uss'), None],
    [('to', 'for', 'ad1', 'ro2', 'ne'), None],
    [('to', 'for', 'ad2', 'cum1', 'uss'), None],
    [('to', 'for', 'ad2', 'cum1', 'ne'), None],
    [('to', 'for', 'ad2', 'cum2', 'uss'), None],
    [('to', 'for', 'ad2', 'cum2', 'ne'), None],
    [('to', 'for', 'ad2', 'ro1', 'uss'), None],
    [('to', 'for', 'ad2', 'ro1', 'ne'), None],
    [('to', 'for', 'ad2', 'ro2', 'uss'), None],
    [('to', 'for', 'ad2', 'ro2', 'ne'), None],
    [('to', 'for', 'athe', 'cum1', 'uss'), None],
    [('to', 'for', 'athe', 'cum1', 'ne'), None],
    [('to', 'for', 'athe', 'cum2', 'uss'), None],
    [('to', 'for', 'athe', 'cum2', 'ne'), None],
    [('to', 'for', 'athe', 'ro1', 'uss'), None],
    [('to', 'for', 'athe', 'ro1', 'ne'), None],
    [('to', 'for', 'athe', 'ro2', 'uss'), None],
    [('to', 'for', 'athe', 'ro2', 'ne'), None],
    [('to', 'for', 'are', 'cum1', 'uss'), None],
    [('to', 'for', 'are', 'cum1', 'ne'), None],
    [('to', 'for', 'are', 'cum2', 'uss'), None],
    [('to', 'for', 'are', 'cum2', 'ne'), None],
    [('to', 'for', 'are', 'ro1', 'uss'), None],
    [('to', 'for', 'are', 'ro1', 'ne'), None],
    [('to', 'for', 'are', 'ro2', 'uss'), None],
    [('to', 'for', 'are', 'ro2', 'ne'), None],
    [('to', 'for', 'de', 'cum1', 'uss'), None],
    [('to', 'for', 'de', 'cum1', 'ne'), None],
    [('to', 'for', 'de', 'cum2', 'uss'), None],
    [('to', 'for', 'de', 'cum2', 'ne'), None],
    [('to', 'for', 'de', 'ro1', 'uss'), None],
    [('to', 'for', 'de', 'ro1', 'ne'), None],
    [('to', 'for', 'de', 'ro2', 'uss'), None],
    [('to', 'for', 'de', 'ro2', 'ne'), None],
    [('to', 'fris', 'ad1', 'cum1', 'uss'), None],
    [('to', 'fris', 'ad1', 'cum1', 'ne'), None],
    [('to', 'fris', 'ad1', 'cum2', 'uss'), None],
    [('to', 'fris', 'ad1', 'cum2', 'ne'), None],
    [('to', 'fris', 'ad1', 'ro1', 'uss'), None],
    [('to', 'fris', 'ad1', 'ro1', 'ne'), None],
    [('to', 'fris', 'ad1', 'ro2', 'uss'), None],
    [('to', 'fris', 'ad1', 'ro2', 'ne'), None],
    [('to', 'fris', 'ad2', 'cum1', 'uss'), None],
    [('to', 'fris', 'ad2', 'cum1', 'ne'), None],
    [('to', 'fris', 'ad2', 'cum2', 'uss'), None],
    [('to', 'fris', 'ad2', 'cum2', 'ne'), None],
    [('to', 'fris', 'ad2', 'ro1', 'uss'), None],
    [('to', 'fris', 'ad2', 'ro1', 'ne'), None],
    [('to', 'fris', 'ad2', 'ro2', 'uss'), None],
    [('to', 'fris', 'ad2', 'ro2', 'ne'), None],
    [('to', 'fris', 'athe', 'cum1', 'uss'), None],
    [('to', 'fris', 'athe', 'cum1', 'ne'), None],
    [('to', 'fris', 'athe', 'cum2', 'uss'), None],
    [('to', 'fris', 'athe', 'cum2', 'ne'), None],
    [('to', 'fris', 'athe', 'ro1', 'uss'), None],
    [('to', 'fris', 'athe', 'ro1', 'ne'), None],
    [('to', 'fris', 'athe', 'ro2', 'uss'), None],
    [('to', 'fris', 'athe', 'ro2', 'ne'), None],
    [('to', 'fris', 'are', 'cum1', 'uss'), None],
    [('to', 'fris', 'are', 'cum1', 'ne'), None],
    [('to', 'fris', 'are', 'cum2', 'uss'), None],
    [('to', 'fris', 'are', 'cum2', 'ne'), None],
    [('to', 'fris', 'are', 'ro1', 'uss'), None],
    [('to', 'fris', 'are', 'ro1', 'ne'), None],
    [('to', 'fris', 'are', 'ro2', 'uss'), None],
    [('to', 'fris', 'are', 'ro2', 'ne'), None],
    [('to', 'fris', 'de', 'cum1', 'uss'), None],
    [('to', 'fris', 'de', 'cum1', 'ne'), None],
    [('to', 'fris', 'de', 'cum2', 'uss'), None],
    [('to', 'fris', 'de', 'cum2', 'ne'), None],
    [('to', 'fris', 'de', 'ro1', 'uss'), None],
    [('to', 'fris', 'de', 'ro1', 'ne'), None],
    [('to', 'fris', 'de', 'ro2', 'uss'), None],
    [('to', 'fris', 'de', 'ro2', 'ne'), None],
    [('to', 'eter', 'ad1', 'cum1', 'uss'), None],
    [('to', 'eter', 'ad1', 'cum1', 'ne'), None],
    [('to', 'eter', 'ad1', 'cum2', 'uss'), None],
    [('to', 'eter', 'ad1', 'cum2', 'ne'), None],
    [('to', 'eter', 'ad1', 'ro1', 'uss'), None],
    [('to', 'eter', 'ad1', 'ro1', 'ne'), None],
    [('to', 'eter', 'ad1', 'ro2', 'uss'), None],
    [('to', 'eter', 'ad1', 'ro2', 'ne'), None],
    [('to', 'eter', 'ad2', 'cum1', 'uss'), None],
    [('to', 'eter', 'ad2', 'cum1', 'ne'), None],
    [('to', 'eter', 'ad2', 'cum2', 'uss'), None],
    [('to', 'eter', 'ad2', 'cum2', 'ne'), None],
    [('to', 'eter', 'ad2', 'ro1', 'uss'), None],
    [('to', 'eter', 'ad2', 'ro1', 'ne'), None],
    [('to', 'eter', 'ad2', 'ro2', 'uss'), None],
    [('to', 'eter', 'ad2', 'ro2', 'ne'), None],
    [('to', 'eter', 'athe', 'cum1', 'uss'), None],
    [('to', 'eter', 'athe', 'cum1', 'ne'), None],
    [('to', 'eter', 'athe', 'cum2', 'uss'), None],
    [('to', 'eter', 'athe', 'cum2', 'ne'), None],
    [('to', 'eter', 'athe', 'ro1', 'uss'), None],
    [('to', 'eter', 'athe', 'ro1', 'ne'), None],
    [('to', 'eter', 'athe', 'ro2', 'uss'), None],
    [('to', 'eter', 'athe', 'ro2', 'ne'), None],
    [('to', 'eter', 'are', 'cum1', 'uss'), None],
    [('to', 'eter', 'are', 'cum1', 'ne'), None],
    [('to', 'eter', 'are', 'cum2', 'uss'), None],
    [('to', 'eter', 'are', 'cum2', 'ne'), None],
    [('to', 'eter', 'are', 'ro1', 'uss'), None],
    [('to', 'eter', 'are', 'ro1', 'ne'), None],
    [('to', 'eter', 'are', 'ro2', 'uss'), None],
    [('to', 'eter', 'are', 'ro2', 'ne'), None],
    [('to', 'eter', 'de', 'cum1', 'uss'), None],
    [('to', 'eter', 'de', 'cum1', 'ne'), None],
    [('to', 'eter', 'de', 'cum2', 'uss'), None],
    [('to', 'eter', 'de', 'cum2', 'ne'), None],
    [('to', 'eter', 'de', 'ro1', 'uss'), None],
    [('to', 'eter', 'de', 'ro1', 'ne'), None],
    [('to', 'eter', 'de', 'ro2', 'uss'), None],
    [('to', 'eter', 'de', 'ro2', 'ne'), None],
    [('to', 'imbe', 'ad1', 'cum1', 'uss'), None],
    [('to', 'imbe', 'ad1', 'cum1', 'ne'), None],
    [('to', 'imbe', 'ad1', 'cum2', 'uss'), None],
    [('to', 'imbe', 'ad1', 'cum2', 'ne'), None],
    [('to', 'imbe', 'ad1', 'ro1', 'uss'), None],
    [('to', 'imbe', 'ad1', 'ro1', 'ne'), None],
    [('to', 'imbe', 'ad1', 'ro2', 'uss'), None],
    [('to', 'imbe', 'ad1', 'ro2', 'ne'), None],
    [('to', 'imbe', 'ad2', 'cum1', 'uss'), None],
    [('to', 'imbe', 'ad2', 'cum1', 'ne'), None],
    [('to', 'imbe', 'ad2', 'cum2', 'uss'), None],
    [('to', 'imbe', 'ad2', 'cum2', 'ne'), None],
    [('to', 'imbe', 'ad2', 'ro1', 'uss'), None],
    [('to', 'imbe', 'ad2', 'ro1', 'ne'), None],
    [('to', 'imbe', 'ad2', 'ro2', 'uss'), None],
    [('to', 'imbe', 'ad2', 'ro2', 'ne'), None],
    [('to', 'imbe', 'athe', 'cum1', 'uss'), None],
    [('to', 'imbe', 'athe', 'cum1', 'ne'), None],
    [('to', 'imbe', 'athe', 'cum2', 'uss'), None],
    [('to', 'imbe', 'athe', 'cum2', 'ne'), None],
    [('to', 'imbe', 'athe', 'ro1', 'uss'), None],
    [('to', 'imbe', 'athe', 'ro1', 'ne'), None],
    [('to', 'imbe', 'athe', 'ro2', 'uss'), None],
    [('to', 'imbe', 'athe', 'ro2', 'ne'), None],
    [('to', 'imbe', 'are', 'cum1', 'uss'), None],
    [('to', 'imbe', 'are', 'cum1', 'ne'), None],
    [('to', 'imbe', 'are', 'cum2', 'uss'), None],
    [('to', 'imbe', 'are', 'cum2', 'ne'), None],
    [('to', 'imbe', 'are', 'ro1', 'uss'), None],
    [('to', 'imbe', 'are', 'ro1', 'ne'), None],
    [('to', 'imbe', 'are', 'ro2', 'uss'), None],
    [('to', 'imbe', 'are', 'ro2', 'ne'), None],
    [('to', 'imbe', 'de', 'cum1', 'uss'), None],
    [('to', 'imbe', 'de', 'cum1', 'ne'), None],
    [('to', 'imbe', 'de', 'cum2', 'uss'), None],
    [('to', 'imbe', 'de', 'cum2', 'ne'), None],
    [('to', 'imbe', 'de', 'ro1', 'uss'), None],
    [('to', 'imbe', 'de', 'ro1', 'ne'), None],
    [('to', 'imbe', 'de', 'ro2', 'uss'), None],
    [('to', 'imbe', 'de', 'ro2', 'ne'), None],
    [('to', 'ess', 'ad1', 'cum1', 'uss'), None],
    [('to', 'ess', 'ad1', 'cum1', 'ne'), None],
    [('to', 'ess', 'ad1', 'cum2', 'uss'), None],
    [('to', 'ess', 'ad1', 'cum2', 'ne'), None],
    [('to', 'ess', 'ad1', 'ro1', 'uss'), None],
    [('to', 'ess', 'ad1', 'ro1', 'ne'), None],
    [('to', 'ess', 'ad1', 'ro2', 'uss'), None],
    [('to', 'ess', 'ad1', 'ro2', 'ne'), None],
    [('to', 'ess', 'ad2', 'cum1', 'uss'), None],
    [('to', 'ess', 'ad2', 'cum1', 'ne'), None],
    [('to', 'ess', 'ad2', 'cum2', 'uss'), None],
    [('to', 'ess', 'ad2', 'cum2', 'ne'), None],
    [('to', 'ess', 'ad2', 'ro1', 'uss'), None],
    [('to', 'ess', 'ad2', 'ro1', 'ne'), None],
    [('to', 'ess', 'ad2', 'ro2', 'uss'), None],
    [('to', 'ess', 'ad2', 'ro2', 'ne'), None],
    [('to', 'ess', 'athe', 'cum1', 'uss'), None],
    [('to', 'ess', 'athe', 'cum1', 'ne'), None],
    [('to', 'ess', 'athe', 'cum2', 'uss'), None],
    [('to', 'ess', 'athe', 'cum2', 'ne'), None],
    [('to', 'ess', 'athe', 'ro1', 'uss'), None],
    [('to', 'ess', 'athe', 'ro1', 'ne'), None],
    [('to', 'ess', 'athe', 'ro2', 'uss'), None],
    [('to', 'ess', 'athe', 'ro2', 'ne'), None],
    [('to', 'ess', 'are', 'cum1', 'uss'), None],
    [('to', 'ess', 'are', 'cum1', 'ne'), None],
    [('to', 'ess', 'are', 'cum2', 'uss'), None],
    [('to', 'ess', 'are', 'cum2', 'ne'), None],
    [('to', 'ess', 'are', 'ro1', 'uss'), None],
    [('to', 'ess', 'are', 'ro1', 'ne'), None],
    [('to', 'ess', 'are', 'ro2', 'uss'), None],
    [('to', 'ess', 'are', 'ro2', 'ne'), None],
    [('to', 'ess', 'de', 'cum1', 'uss'), None],
    [('to', 'ess', 'de', 'cum1', 'ne'), None],
    [('to', 'ess', 'de', 'cum2', 'uss'), None],
    [('to', 'ess', 'de', 'cum2', 'ne'), None],
    [('to', 'ess', 'de', 'ro1', 'uss'), None],
    [('to', 'ess', 'de', 'ro1', 'ne'), None],
    [('to', 'ess', 'de', 'ro2', 'uss'), None],
    [('to', 'ess', 'de', 'ro2', 'ne'), None],
    [('to', 'fo', 'ad1', 'cum1', 'uss'), None],
    [('to', 'fo', 'ad1', 'cum1', 'ne'), None],
    [('to', 'fo', 'ad1', 'cum2', 'uss'), None],
    [('to', 'fo', 'ad1', 'cum2', 'ne'), None],
    [('to', 'fo', 'ad1', 'ro1', 'uss'), None],
    [('to', 'fo', 'ad1', 'ro1', 'ne'), None],
    [('to', 'fo', 'ad1', 'ro2', 'uss'), None],
    [('to', 'fo', 'ad1', 'ro2', 'ne'), None],
    [('to', 'fo', 'ad2', 'cum1', 'uss'), None],
    [('to', 'fo', 'ad2', 'cum1', 'ne'), None],
    [('to', 'fo', 'ad2', 'cum2', 'uss'), None],
    [('to', 'fo', 'ad2', 'cum2', 'ne'), None],
    [('to', 'fo', 'ad2', 'ro1', 'uss'), None],
    [('to', 'fo', 'ad2', 'ro1', 'ne'), None],
    [('to', 'fo', 'ad2', 'ro2', 'uss'), None],
    [('to', 'fo', 'ad2', 'ro2', 'ne'), None],
    [('to', 'fo', 'athe', 'cum1', 'uss'), None],
    [('to', 'fo', 'athe', 'cum1', 'ne'), None],
    [('to', 'fo', 'athe', 'cum2', 'uss'), None],
    [('to', 'fo', 'athe', 'cum2', 'ne'), None],
    [('to', 'fo', 'athe', 'ro1', 'uss'), None],
    [('to', 'fo', 'athe', 'ro1', 'ne'), None],
    [('to', 'fo', 'athe', 'ro2', 'uss'), None],
    [('to', 'fo', 'athe', 'ro2', 'ne'), None],
    [('to', 'fo', 'are', 'cum1', 'uss'), None],
    [('to', 'fo', 'are', 'cum1', 'ne'), None],
    [('to', 'fo', 'are', 'cum2', 'uss'), None],
    [('to', 'fo', 'are', 'cum2', 'ne'), None],
    [('to', 'fo', 'are', 'ro1', 'uss'), None],
    [('to', 'fo', 'are', 'ro1', 'ne'), None],
    [('to', 'fo', 'are', 'ro2', 'uss'), None],
    [('to', 'fo', 'are', 'ro2', 'ne'), None],
    [('to', 'fo', 'de', 'cum1', 'uss'), None],
    [('to', 'fo', 'de', 'cum1', 'ne'), None],
    [('to', 'fo', 'de', 'cum2', 'uss'), None],
    [('to', 'fo', 'de', 'cum2', 'ne'), None],
    [('to', 'fo', 'de', 'ro1', 'uss'), None],
    [('to', 'fo', 'de', 'ro1', 'ne'), None],
    [('to', 'fo', 'de', 'ro2', 'uss'), None],
    [('to', 'fo', 'de', 'ro2', 'ne'), None],
    [('to', 'inde', 'ad1', 'cum1', 'uss'), None],
    [('to', 'inde', 'ad1', 'cum1', 'ne'), None],
    [('to', 'inde', 'ad1', 'cum2', 'uss'), None],
    [('to', 'inde', 'ad1', 'cum2', 'ne'), None],
    [('to', 'inde', 'ad1', 'ro1', 'uss'), None],
    [('to', 'inde', 'ad1', 'ro1', 'ne'), None],
    [('to', 'inde', 'ad1', 'ro2', 'uss'), None],
    [('to', 'inde', 'ad1', 'ro2', 'ne'), None],
    [('to', 'inde', 'ad2', 'cum1', 'uss'), None],
    [('to', 'inde', 'ad2', 'cum1', 'ne'), None],
    [('to', 'inde', 'ad2', 'cum2', 'uss'), None],
    [('to', 'inde', 'ad2', 'cum2', 'ne'), None],
    [('to', 'inde', 'ad2', 'ro1', 'uss'), None],
    [('to', 'inde', 'ad2', 'ro1', 'ne'), None],
    [('to', 'inde', 'ad2', 'ro2', 'uss'), None],
    [('to', 'inde', 'ad2', 'ro2', 'ne'), None],
    [('to', 'inde', 'athe', 'cum1', 'uss'), None],
    [('to', 'inde', 'athe', 'cum1', 'ne'), None],
    [('to', 'inde', 'athe', 'cum2', 'uss'), None],
    [('to', 'inde', 'athe', 'cum2', 'ne'), None],
    [('to', 'inde', 'athe', 'ro1', 'uss'), None],
    [('to', 'inde', 'athe', 'ro1', 'ne'), None],
    [('to', 'inde', 'athe', 'ro2', 'uss'), None],
    [('to', 'inde', 'athe', 'ro2', 'ne'), None],
    [('to', 'inde', 'are', 'cum1', 'uss'), None],
    [('to', 'inde', 'are', 'cum1', 'ne'), None],
    [('to', 'inde', 'are', 'cum2', 'uss'), None],
    [('to', 'inde', 'are', 'cum2', 'ne'), None],
    [('to', 'inde', 'are', 'ro1', 'uss'), None],
    [('to', 'inde', 'are', 'ro1', 'ne'), None],
    [('to', 'inde', 'are', 'ro2', 'uss'), None],
    [('to', 'inde', 'are', 'ro2', 'ne'), None],
    [('to', 'inde', 'de', 'cum1', 'uss'), None],
    [('to', 'inde', 'de', 'cum1', 'ne'), None],
    [('to', 'inde', 'de', 'cum2', 'uss'), None],
    [('to', 'inde', 'de', 'cum2', 'ne'), None],
    [('to', 'inde', 'de', 'ro1', 'uss'), None],
    [('to', 'inde', 'de', 'ro1', 'ne'), None],
    [('to', 'inde', 'de', 'ro2', 'uss'), None],
    [('to', 'inde', 'de', 'ro2', 'ne'), None],
        )

