import random

#could so-called secondary composition cases in native vocabulary (McCone 1997:90-1) be burps from a bigrammatic grammar? 
#should make separate lists of native/loan secondary orderings

combination_cnt = (
    [('RED',), None],
    [('ma',), None],
    [('Pi',), None],
    [('mag',), None],
    [('ka',), None],
    [('si',), None],
    [('pag',), None],
    [('pa',), None],
    [('ki',), None],
    [('RED', 'ma'), None],
    [('RED', 'Pi'), None],
    [('RED', 'mag'), None],
    [('RED', 'ka'), None],
    [('RED', 'si'), None],
    [('RED', 'pag'), None],
    [('RED', 'pa'), None],
    [('RED', 'ki'), None],
    [('ma', 'Pi'), None],
    [('ma', 'mag'), None],
    [('ma', 'ka'), None],
    [('ma', 'si'), None],
    [('ma', 'pag'), None],
    [('ma', 'pa'), None],
    [('ma', 'ki'), None],
    [('Pi', 'ka'), None],
    [('Pi', 'si'), None],
    [('mag', 'ka'), None],
    [('mag', 'si'), None],
    [('Pi', 'pag'), None],
    [('mag', 'pag'), None],
    [('Pi', 'pa'), None],
    [('mag', 'pa'), None],
    [('Pi', 'ki'), None],
    [('mag', 'ki'), None],
    [('ka', 'pag'), None],
    [('si', 'pag'), None],
    [('ka', 'pa'), None],
    [('si', 'pa'), None],
    [('ka', 'ki'), None],
    [('si', 'ki'), None],
    [('pag', 'pa'), None],
    [('pag', 'ki'), None],
    [('pa', 'ki'), None],
    [('RED', 'ma', 'Pi'), None],
    [('RED', 'ma', 'mag'), None],
    [('RED', 'ma', 'ka'), None],
    [('RED', 'ma', 'si'), None],
    [('RED', 'ma', 'pag'), None],
    [('RED', 'ma', 'pa'), None],
    [('RED', 'ma', 'ki'), None],
    [('RED', 'Pi', 'ka'), None],
    [('RED', 'Pi', 'si'), None],
    [('RED', 'mag', 'ka'), None],
    [('RED', 'mag', 'si'), None],
    [('RED', 'Pi', 'pag'), None],
    [('RED', 'mag', 'pag'), None],
    [('RED', 'Pi', 'pa'), None],
    [('RED', 'mag', 'pa'), None],
    [('RED', 'Pi', 'ki'), None],
    [('RED', 'mag', 'ki'), None],
    [('RED', 'ka', 'pag'), None],
    [('RED', 'si', 'pag'), None],
    [('RED', 'ka', 'pa'), None],
    [('RED', 'si', 'pa'), None],
    [('RED', 'ka', 'ki'), None],
    [('RED', 'si', 'ki'), None],
    [('RED', 'pag', 'pa'), None],
    [('RED', 'pag', 'ki'), None],
    [('RED', 'pa', 'ki'), None],
    [('ma', 'Pi', 'ka'), None],
    [('ma', 'Pi', 'si'), None],
    [('ma', 'mag', 'ka'), None],
    [('ma', 'mag', 'si'), None],
    [('ma', 'Pi', 'pag'), None],
    [('ma', 'mag', 'pag'), None],
    [('ma', 'Pi', 'pa'), None],
    [('ma', 'mag', 'pa'), None],
    [('ma', 'Pi', 'ki'), None],
    [('ma', 'mag', 'ki'), None],
    [('ma', 'ka', 'pag'), None],
    [('ma', 'si', 'pag'), None],
    [('ma', 'ka', 'pa'), None],
    [('ma', 'si', 'pa'), None],
    [('ma', 'ka', 'ki'), None],
    [('ma', 'si', 'ki'), None],
    [('ma', 'pag', 'pa'), None],
    [('ma', 'pag', 'ki'), None],
    [('ma', 'pa', 'ki'), None],
    [('Pi', 'ka', 'pag'), None],
    [('Pi', 'si', 'pag'), None],
    [('mag', 'ka', 'pag'), None],
    [('mag', 'si', 'pag'), None],
    [('Pi', 'ka', 'pa'), None],
    [('Pi', 'si', 'pa'), None],
    [('mag', 'ka', 'pa'), None],
    [('mag', 'si', 'pa'), None],
    [('Pi', 'ka', 'ki'), None],
    [('Pi', 'si', 'ki'), None],
    [('mag', 'ka', 'ki'), None],
    [('mag', 'si', 'ki'), None],
    [('Pi', 'pag', 'pa'), None],
    [('mag', 'pag', 'pa'), None],
    [('Pi', 'pag', 'ki'), None],
    [('mag', 'pag', 'ki'), None],
    [('Pi', 'pa', 'ki'), None],
    [('mag', 'pa', 'ki'), None],
    [('ka', 'pag', 'pa'), None],
    [('si', 'pag', 'pa'), None],
    [('ka', 'pag', 'ki'), None],
    [('si', 'pag', 'ki'), None],
    [('ka', 'pa', 'ki'), None],
    [('si', 'pa', 'ki'), None],
    [('pag', 'pa', 'ki'), None],
    [('RED', 'ma', 'Pi', 'ka'), None],
    [('RED', 'ma', 'Pi', 'si'), None],
    [('RED', 'ma', 'mag', 'ka'), None],
    [('RED', 'ma', 'mag', 'si'), None],
    [('RED', 'ma', 'Pi', 'pag'), None],
    [('RED', 'ma', 'mag', 'pag'), None],
    [('RED', 'ma', 'Pi', 'pa'), None],
    [('RED', 'ma', 'mag', 'pa'), None],
    [('RED', 'ma', 'Pi', 'ki'), None],
    [('RED', 'ma', 'mag', 'ki'), None],
    [('RED', 'ma', 'ka', 'pag'), None],
    [('RED', 'ma', 'si', 'pag'), None],
    [('RED', 'ma', 'ka', 'pa'), None],
    [('RED', 'ma', 'si', 'pa'), None],
    [('RED', 'ma', 'ka', 'ki'), None],
    [('RED', 'ma', 'si', 'ki'), None],
    [('RED', 'ma', 'pag', 'pa'), None],
    [('RED', 'ma', 'pag', 'ki'), None],
    [('RED', 'ma', 'pa', 'ki'), None],
    [('RED', 'Pi', 'ka', 'pag'), None],
    [('RED', 'Pi', 'si', 'pag'), None],
    [('RED', 'mag', 'ka', 'pag'), None],
    [('RED', 'mag', 'si', 'pag'), None],
    [('RED', 'Pi', 'ka', 'pa'), None],
    [('RED', 'Pi', 'si', 'pa'), None],
    [('RED', 'mag', 'ka', 'pa'), None],
    [('RED', 'mag', 'si', 'pa'), None],
    [('RED', 'Pi', 'ka', 'ki'), None],
    [('RED', 'Pi', 'si', 'ki'), None],
    [('RED', 'mag', 'ka', 'ki'), None],
    [('RED', 'mag', 'si', 'ki'), None],
    [('RED', 'Pi', 'pag', 'pa'), None],
    [('RED', 'mag', 'pag', 'pa'), None],
    [('RED', 'Pi', 'pag', 'ki'), None],
    [('RED', 'mag', 'pag', 'ki'), None],
    [('RED', 'Pi', 'pa', 'ki'), None],
    [('RED', 'mag', 'pa', 'ki'), None],
    [('RED', 'ka', 'pag', 'pa'), None],
    [('RED', 'si', 'pag', 'pa'), None],
    [('RED', 'ka', 'pag', 'ki'), None],
    [('RED', 'si', 'pag', 'ki'), None],
    [('RED', 'ka', 'pa', 'ki'), None],
    [('RED', 'si', 'pa', 'ki'), None],
    [('RED', 'pag', 'pa', 'ki'), None],
    [('ma', 'Pi', 'ka', 'pag'), None],
    [('ma', 'Pi', 'si', 'pag'), None],
    [('ma', 'mag', 'ka', 'pag'), None],
    [('ma', 'mag', 'si', 'pag'), None],
    [('ma', 'Pi', 'ka', 'pa'), None],
    [('ma', 'Pi', 'si', 'pa'), None],
    [('ma', 'mag', 'ka', 'pa'), None],
    [('ma', 'mag', 'si', 'pa'), None],
    [('ma', 'Pi', 'ka', 'ki'), None],
    [('ma', 'Pi', 'si', 'ki'), None],
    [('ma', 'mag', 'ka', 'ki'), None],
    [('ma', 'mag', 'si', 'ki'), None],
    [('ma', 'Pi', 'pag', 'pa'), None],
    [('ma', 'mag', 'pag', 'pa'), None],
    [('ma', 'Pi', 'pag', 'ki'), None],
    [('ma', 'mag', 'pag', 'ki'), None],
    [('ma', 'Pi', 'pa', 'ki'), None],
    [('ma', 'mag', 'pa', 'ki'), None],
    [('ma', 'ka', 'pag', 'pa'), None],
    [('ma', 'si', 'pag', 'pa'), None],
    [('ma', 'ka', 'pag', 'ki'), None],
    [('ma', 'si', 'pag', 'ki'), None],
    [('ma', 'ka', 'pa', 'ki'), None],
    [('ma', 'si', 'pa', 'ki'), None],
    [('ma', 'pag', 'pa', 'ki'), None],
    [('Pi', 'ka', 'pag', 'pa'), None],
    [('Pi', 'si', 'pag', 'pa'), None],
    [('mag', 'ka', 'pag', 'pa'), None],
    [('mag', 'si', 'pag', 'pa'), None],
    [('Pi', 'ka', 'pag', 'ki'), None],
    [('Pi', 'si', 'pag', 'ki'), None],
    [('mag', 'ka', 'pag', 'ki'), None],
    [('mag', 'si', 'pag', 'ki'), None],
    [('Pi', 'ka', 'pa', 'ki'), None],
    [('Pi', 'si', 'pa', 'ki'), None],
    [('mag', 'ka', 'pa', 'ki'), None],
    [('mag', 'si', 'pa', 'ki'), None],
    [('Pi', 'pag', 'pa', 'ki'), None],
    [('mag', 'pag', 'pa', 'ki'), None],
    [('ka', 'pag', 'pa', 'ki'), None],
    [('si', 'pag', 'pa', 'ki'), None],
    [('RED', 'ma', 'Pi', 'ka', 'pag'), None],
    [('RED', 'ma', 'Pi', 'si', 'pag'), None],
    [('RED', 'ma', 'mag', 'ka', 'pag'), None],
    [('RED', 'ma', 'mag', 'si', 'pag'), None],
    [('RED', 'ma', 'Pi', 'ka', 'pa'), None],
    [('RED', 'ma', 'Pi', 'si', 'pa'), None],
    [('RED', 'ma', 'mag', 'ka', 'pa'), None],
    [('RED', 'ma', 'mag', 'si', 'pa'), None],
    [('RED', 'ma', 'Pi', 'ka', 'ki'), None],
    [('RED', 'ma', 'Pi', 'si', 'ki'), None],
    [('RED', 'ma', 'mag', 'ka', 'ki'), None],
    [('RED', 'ma', 'mag', 'si', 'ki'), None],
    [('RED', 'ma', 'Pi', 'pag', 'pa'), None],
    [('RED', 'ma', 'mag', 'pag', 'pa'), None],
    [('RED', 'ma', 'Pi', 'pag', 'ki'), None],
    [('RED', 'ma', 'mag', 'pag', 'ki'), None],
    [('RED', 'ma', 'Pi', 'pa', 'ki'), None],
    [('RED', 'ma', 'mag', 'pa', 'ki'), None],
    [('RED', 'ma', 'ka', 'pag', 'pa'), None],
    [('RED', 'ma', 'si', 'pag', 'pa'), None],
    [('RED', 'ma', 'ka', 'pag', 'ki'), None],
    [('RED', 'ma', 'si', 'pag', 'ki'), None],
    [('RED', 'ma', 'ka', 'pa', 'ki'), None],
    [('RED', 'ma', 'si', 'pa', 'ki'), None],
    [('RED', 'ma', 'pag', 'pa', 'ki'), None],
    [('RED', 'Pi', 'ka', 'pag', 'pa'), None],
    [('RED', 'Pi', 'si', 'pag', 'pa'), None],
    [('RED', 'mag', 'ka', 'pag', 'pa'), None],
    [('RED', 'mag', 'si', 'pag', 'pa'), None],
    [('RED', 'Pi', 'ka', 'pag', 'ki'), None],
    [('RED', 'Pi', 'si', 'pag', 'ki'), None],
    [('RED', 'mag', 'ka', 'pag', 'ki'), None],
    [('RED', 'mag', 'si', 'pag', 'ki'), None],
    [('RED', 'Pi', 'ka', 'pa', 'ki'), None],
    [('RED', 'Pi', 'si', 'pa', 'ki'), None],
    [('RED', 'mag', 'ka', 'pa', 'ki'), None],
    [('RED', 'mag', 'si', 'pa', 'ki'), None],
    [('RED', 'Pi', 'pag', 'pa', 'ki'), None],
    [('RED', 'mag', 'pag', 'pa', 'ki'), None],
    [('RED', 'ka', 'pag', 'pa', 'ki'), None],
    [('RED', 'si', 'pag', 'pa', 'ki'), None],
    [('ma', 'Pi', 'ka', 'pag', 'pa'), None],
    [('ma', 'Pi', 'si', 'pag', 'pa'), None],
    [('ma', 'mag', 'ka', 'pag', 'pa'), None],
    [('ma', 'mag', 'si', 'pag', 'pa'), None],
    [('ma', 'Pi', 'ka', 'pag', 'ki'), None],
    [('ma', 'Pi', 'si', 'pag', 'ki'), None],
    [('ma', 'mag', 'ka', 'pag', 'ki'), None],
    [('ma', 'mag', 'si', 'pag', 'ki'), None],
    [('ma', 'Pi', 'ka', 'pa', 'ki'), None],
    [('ma', 'Pi', 'si', 'pa', 'ki'), None],
    [('ma', 'mag', 'ka', 'pa', 'ki'), None],
    [('ma', 'mag', 'si', 'pa', 'ki'), None],
    [('ma', 'Pi', 'pag', 'pa', 'ki'), None],
    [('ma', 'mag', 'pag', 'pa', 'ki'), None],
    [('ma', 'ka', 'pag', 'pa', 'ki'), None],
    [('ma', 'si', 'pag', 'pa', 'ki'), None],
    [('Pi', 'ka', 'pag', 'pa', 'ki'), None],
    [('Pi', 'si', 'pag', 'pa', 'ki'), None],
    [('mag', 'ka', 'pag', 'pa', 'ki'), None],
    [('mag', 'si', 'pag', 'pa', 'ki'), None],
    [('RED', 'ma', 'Pi', 'ka', 'pag', 'pa'), None],
    [('RED', 'ma', 'Pi', 'si', 'pag', 'pa'), None],
    [('RED', 'ma', 'mag', 'ka', 'pag', 'pa'), None],
    [('RED', 'ma', 'mag', 'si', 'pag', 'pa'), None],
    [('RED', 'ma', 'Pi', 'ka', 'pag', 'ki'), None],
    [('RED', 'ma', 'Pi', 'si', 'pag', 'ki'), None],
    [('RED', 'ma', 'mag', 'ka', 'pag', 'ki'), None],
    [('RED', 'ma', 'mag', 'si', 'pag', 'ki'), None],
    [('RED', 'ma', 'Pi', 'ka', 'pa', 'ki'), None],
    [('RED', 'ma', 'Pi', 'si', 'pa', 'ki'), None],
    [('RED', 'ma', 'mag', 'ka', 'pa', 'ki'), None],
    [('RED', 'ma', 'mag', 'si', 'pa', 'ki'), None],
    [('RED', 'ma', 'Pi', 'pag', 'pa', 'ki'), None],
    [('RED', 'ma', 'mag', 'pag', 'pa', 'ki'), None],
    [('RED', 'ma', 'ka', 'pag', 'pa', 'ki'), None],
    [('RED', 'ma', 'si', 'pag', 'pa', 'ki'), None],
    [('RED', 'Pi', 'ka', 'pag', 'pa', 'ki'), None],
    [('RED', 'Pi', 'si', 'pag', 'pa', 'ki'), None],
    [('RED', 'mag', 'ka', 'pag', 'pa', 'ki'), None],
    [('RED', 'mag', 'si', 'pag', 'pa', 'ki'), None],
    [('ma', 'Pi', 'ka', 'pag', 'pa', 'ki'), None],
    [('ma', 'Pi', 'si', 'pag', 'pa', 'ki'), None],
    [('ma', 'mag', 'ka', 'pag', 'pa', 'ki'), None],
    [('ma', 'mag', 'si', 'pag', 'pa', 'ki'), None],
    [('RED', 'ma', 'Pi', 'ka', 'pag', 'pa', 'ki'), None],
    [('RED', 'ma', 'Pi', 'si', 'pag', 'pa', 'ki'), None],
    [('RED', 'ma', 'mag', 'ka', 'pag', 'pa', 'ki'), None],
    [('RED', 'ma', 'mag', 'si', 'pag', 'pa', 'ki'), None],
)
